name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check npm version
        run: npm -v

      - name: Install node-sass with Taobao mirror
        run: |
          export SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
          npm install node-sass

      - name: Set npm registry to Taobao mirror
        run: npm config set registry https://registry.npm.taobao.org

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
